[package]
name = "pct-enc"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
rand = "0.9"
bytemuck = { version = "1" }

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "bench"
harness = false
