[workspace]
members = ["aoc-2022", "cuter-nucleotides", "trim-line-comments"]
resolver = "3"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "allow"

[workspace.lints.clippy]
missing_safety_doc = "allow"
unusual_byte_groupings = "allow"
